version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "[GITHUB-ACTIONS] "
    rebase-strategy: "disabled"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      pip:
        patterns:
          - "*"
    commit-message:
      prefix: "[PIP] "
    rebase-strategy: "disabled"
    versioning-strategy: increase
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      terraform:
        patterns:
          - "*"
    commit-message:
      prefix: "[TERRAFORM] "
    rebase-strategy: "disabled"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
