version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[gha] "
    open-pull-requests-limit: 2
    rebase-strategy: "disabled"
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[pip] "
    open-pull-requests-limit: 2
    rebase-strategy: "disabled"
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[terraform] "
    open-pull-requests-limit: 2
    rebase-strategy: "disabled"
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
