version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      timezone: "America/Los_Angeles"
      cronjob: "1-15 20 * * 6"
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "[GITHUB-ACTIONS] "
    rebase-strategy: "disabled"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: pip
    directory: /
    schedule:
      timezone: "America/Los_Angeles"
      cronjob: "16-30 20 * * 6"
    open-pull-requests-limit: 1
    groups:
      pip:
        patterns:
          - "*"
    commit-message:
      prefix: "[PIP] "
    rebase-strategy: "disabled"
    versioning-strategy: increase
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

