version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "[GHA-SEC-UPDATES] "
    rebase-strategy: "disabled"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "[PIP-SEC-UPDATES] "
    rebase-strategy: "disabled"
    versioning-strategy: increase
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "[TF-SEC-UPDATES] "
    rebase-strategy: "disabled"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
