---
# NOTE: this file is managed by terraform

changelog:
  exclude:
    authors:
      - tagdots-owner
      - tagdots-dev-terraform-github
      - tagdots-terraform-github
  categories:
    - title: "🚀 New features"
      labels:
        - feature
    - title: "🎉 Change features"
      labels:
        - enhancement
    - title: "🐛 Fixes"
      labels:
        - hotfix
        - bugfix
        - dependencies
    - title: "👒 Others"
      labels:
        - build
        - documentation
        - style
        - test
