---
# NOTE: this file is managed by terraform

name: CICD

on:  # yamllint disable-line rule:truthy
  pull_request:

    branches:
      - main

    types:
      - closed
      - edited
      - opened
      - synchronize

  push:
    branches:
      - test-*

  workflow_dispatch:

permissions:
  contents: write

jobs:

  pre-commit:
    uses: ./.github/workflows/reusable-pre-commit.yaml

  build-and-test:
    uses: ./.github/workflows/reusable-testings.yaml

  release:
    # condition: pull request is closed
    if: ${{ startsWith(github.head_ref, 'release/') && github.event.pull_request.state == 'closed' }}

    needs: [pre-commit, build-and-test]

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: python -m pip install -e .[test]

    - name: Get outputs from build-and-test
      run: echo "${{ toJson(needs.build-and-test.outputs) }}"

    - name: Download distributions
      id: artifact-download
      uses: actions/download-artifact@v4
      with:
        path: dist/

    - name: Get dist directory
      run: |
        ls -l dist/
        tree dist/

    - name: Git commands
      run: |
        # get git command results
        git remote -v
        git ls-remote --tags origin
        git status
