---

name: CICD

on:  # yamllint disable-line rule:truthy
  pull_request:

    branches:
      - main

    types:
      - closed
      - edited
      - opened
      - synchronize

  push:
    branches:
      - test-*

  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12.10'

permissions:
  contents: write

jobs:

  build-test:
    uses: ./.github/workflows/reusable-testings.yaml

  git-tag-push:
    # condition: pull request is merged and closed
    if: ${{ startsWith(github.head_ref, 'release/') && github.event.pull_request.state == 'closed' }}

    needs: [build-test]

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - shell: bash
      run: |
        # create and push a lightweight tag
        git tag ${{ needs.build-test.outputs.BUILD_VERSION }}
        git push origin ${{ needs.build-test.outputs.BUILD_VERSION }}

  pypi-test-publish:

    needs: [git-tag-push]

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - run: |
        # install dependencies
        python -m pip install --upgrade pip
        python -m pip install build twine

    - name: Download distributions
      id: artifact-download
      uses: actions/download-artifact@v4
      with:
        path: dist/

    - name: Check upload distributions
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TEST_PASSWORD }}
        TWINE_REPOSITORY_URL: "https://test.pypi.org/legacy/"
      run: |
        # publish to test.pypi.org
        tree dist/
        python -m twine check dist/artifact/*
        python -m twine upload dist/artifact/* --username __token__ --password ${{ secrets.PYPI_PASSWORD }}

    # - name: Publish package distributions to TestPyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     package-dir: dist/artifact/
    #     repository-url: https://test.pypi.org/legacy/
    #     password: ${{ secrets.PYPI_PASSWORD }}
    #     verbose: true

  pypi-test-validate:

    needs: [pypi-test-publish]

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - run: |
        # download from test.pypi.org
        # python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ pkg-15903
        # python -m twine upload --repository testpypi dist/artifact/*
        pip list
        echo "hello world"
