---
# NOTE: this file is managed by terraform

name: CICD

on:  # yamllint disable-line rule:truthy
  pull_request:

    branches:
      - main

    types:
      - closed
      - edited
      - opened

  push:
    branches:
      - test-*

  workflow_dispatch:

permissions:
  contents: read

jobs:

  pre-commit:
    uses: ./.github/workflows/reusable-pre-commit.yaml

  build-and-tests:
    uses: ./.github/workflows/reusable-testings.yaml

  release:
    if: startsWith(github.ref_name, 'test')

    runs-on: ubuntu-latest
    needs: [pre-commit, build-and-tests]
    steps:

    - name: say hello
      run: echo "hello"

    - name: get Github Object
      run: |
        echo "${{ toJson(github) }}"

    - name: get job result - pre-commit
      run: |
        echo "${{ needs.pre-commit.result }}"

    - name: get job result - build-and-tests
      run: |
        echo "${{ needs.build-and-tests.result }}"

    - name: get job - build-and-tests - result and process
      if: "${{ needs.build-and-tests.result }} == 'success'"
      run: |
        echo "${{ toJson(needs.build-and-tests.outputs) }}"
        echo "testing 123"
