---
# NOTE: this file is managed by terraform

name: cron-tasks

on:
  schedule:
    - cron: '30 22 * * 6'

  workflow_dispatch:

permissions:
    actions: read
    contents: read
    issues: read
    pull-requests: read

jobs:
  # https://github.com/Mattraks/delete-workflow-runs
  stale-workflows:

    permissions:
      contents: read
      actions: write

    runs-on: ubuntu-latest

    outputs:
      JB_NAME: ${{ steps.set-step.outputs.JB_NAME }}
      OUTCOME: ${{ steps.set-step.outputs.OUTCOME }}

    steps:

    - id: stale-workflows
      uses: Mattraks/delete-workflow-runs@39f0bbed25d76b34de5594dceab824811479e5de # v2.0.6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 5
        keep_minimum_runs: 8

    - shell: bash
      id: set-step
      run: |
        echo "JB_NAME=stale-workflow"                       >> "$GITHUB_OUTPUT"
        echo "OUTCOME=${{ steps.stale-workflows.outcome }}" >> "$GITHUB_OUTPUT"

  # https://github.com/actions/stale
  stale-issues-prs:

    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    outputs:
      JB_NAME: ${{ steps.set-step.outputs.JB_NAME }}
      OUTCOME: ${{ steps.set-step.outputs.OUTCOME }}

    steps:

    - id: stale-issues-prs
      uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
      with:
        stale-issue-message: 'This issue is stale because it has been open 3 days with no activity. Remove stale label or comment or this will be closed in 3 days.'
        days-before-stale: 4
        days-before-close: 3

    - shell: bash
      id: set-step
      run: |
        echo "JB_NAME=stale-issue-pr"                        >> "$GITHUB_OUTPUT"
        echo "OUTCOME=${{ steps.stale-issues-prs.outcome }}" >> "$GITHUB_OUTPUT"

  # https://github.com/crs-k/stale-branches
  stale-branches:

    permissions:
      issues: write
      contents: write

    runs-on: ubuntu-latest

    outputs:
      JB_NAME: ${{ steps.set-step.outputs.JB_NAME }}
      OUTCOME: ${{ steps.set-step.outputs.OUTCOME }}

    steps:

    - id: stale-branches
      uses: crs-k/stale-branches@ee199d60e5020e819dd84fea8c0d4f83c161a590 # v8.1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 8
        days-before-delete: 10
        pr-check: true

    - shell: bash
      id: set-step
      run: |
        echo "JB_NAME=stale-branch"                                >> "$GITHUB_OUTPUT"
        echo "OUTCOME=${{ toJson(steps.stale-branches.outcome) }}" >> "$GITHUB_OUTPUT"

  notify-slack:
    if: always()
    needs: [stale-workflows, stale-issues-prs, stale-branches]

    runs-on: ubuntu-latest

    steps:

    - name: Post message to Slack
      uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_CRON_TASKS }}"
          text: "
              *Repository : ${{ github.repository }}*\n
              *Workflow   : ${{ github.workflow }}*
              ```
              URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\n
              Job: ${{ needs.stale-workflows.outputs.JB_NAME }} (${{ needs.stale-workflows.outputs.OUTCOME }})\n
              Job: ${{ needs.stale-issues-prs.outputs.JB_NAME }} (${{ needs.stale-issues-prs.outputs.OUTCOME }})\n
              Job: ${{ needs.stale-branches.outputs.JB_NAME }} (${{ needs.stale-branches.outputs.OUTCOME }})
              ```"
