name: cron-stale

on:
  schedule:
    - cron: '30 22 * * *'

  workflow_dispatch:

jobs:
  # https://github.com/Mattraks/delete-workflow-runs
  stale-workflows:
    runs-on: ubuntu-latest
    steps:
      - id: stale-workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 14
          keep_minimum_runs: 6

      - name: Post message to Slack
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
          payload: |
            channel: "${{ secrets.SECRET_SLACK_CHANNEL_CRON_TASKS }}"
            text: "🗑️ JOB: ${{ github.job }} - ${{ toJson(steps.stale-workflows) }}"

  # https://github.com/actions/stale
  stale-issues-prs:
    runs-on: ubuntu-latest
    steps:
    - id: stale-issues-prs
      uses: actions/stale@v9
      with:
        stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
        days-before-stale: 2
        days-before-close: 1

    - name: Post message to Slack
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_CRON_TASKS }}"
          text: "🗑️ JOB: ${{ github.job }} - ${{ toJson(steps.stale-issues-prs) }}"

  # https://github.com/crs-k/stale-branches
  stale-branches:
    runs-on: ubuntu-latest
    steps:
    - id: stale-branches
      uses: crs-k/stale-branches@v7
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 30
        days-before-delete: 45
        pr-check: true

    - name: Post message to Slack
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_CRON_TASKS }}"
          text: "🗑️ JOB: ${{ github.job }} - ${{ toJson(steps.stale-branches) }}"
