name: cron-stale

on:
  schedule:
    - cron: '30 22 * * *'

  workflow_dispatch:

jobs:
  # https://github.com/Mattraks/delete-workflow-runs
  stale-workflow:
    runs-on: ubuntu-latest

    outputs:
      WF_NAME: ${{ steps.set-step.outputs.WF_NAME }}
      OUTCOME: ${{ steps.set-step.outputs.OUTCOME }}

    steps:
    - id: stale-workflows
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 14
        keep_minimum_runs: 6

    - shell: bash
      id: set-step
      # checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
      run: |
        echo "WF_NAME=stale-workflow"                       >> "$GITHUB_OUTPUT"
        echo "OUTCOME=${{ steps.stale-workflows.outcome }}" >> "$GITHUB_OUTPUT"

  # https://github.com/actions/stale
  stale-issue-pr:
    runs-on: ubuntu-latest

    outputs:
      WF_NAME: ${{ steps.set-step.outputs.WF_NAME }}
      OUTCOME: ${{ steps.set-step.outputs.OUTCOME }}

    steps:
    - id: stale-issues-prs
      uses: actions/stale@v9
      with:
        stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
        days-before-stale: 2
        days-before-close: 1

    - shell: bash
      # checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
      id: set-step
      run: |
        echo "WF_NAME=stale-issue-pr"                        >> "$GITHUB_OUTPUT"
        echo "OUTCOME=${{ steps.stale-issues-prs.outcome }}" >> "$GITHUB_OUTPUT"


  # https://github.com/crs-k/stale-branches
  stale-branch:
    runs-on: ubuntu-latest

    outputs:
      WF_NAME: ${{ steps.set-step.outputs.WF_NAME }}
      OUTCOME: ${{ steps.set-step.outputs.OUTCOME }}

    steps:
    - id: stale-branches
      uses: crs-k/stale-branches@v7.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 30
        days-before-delete: 45
        pr-check: true

    - shell: bash
      # checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
      id: set-step
      run: |
        exit 1
        echo "WF_NAME=stale-branch"                        >> "$GITHUB_OUTPUT"
        echo "OUTCOME=${{ steps.stale-branches.outcome }}" >> "$GITHUB_OUTPUT"

  notify-slack:
    if: always()
    needs: [stale-workflow, stale-issue-pr, stale-branch]

    runs-on: ubuntu-latest

    steps:

    - name: Post message to Slack
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_CRON_TASKS }}"
          text: "
              *Workflow: ${{ github.workflow }}*\n
              ```
              URL     : https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\n
              Job     : ${{ needs.stale-workflow.outputs.WF_NAME }}\n
              Result  : ${{ needs.stale-workflow.outputs.OUTCOME }}\n
              Job     : ${{ needs.stale-issue-pr.outputs.WF_NAME }}\n
              Result  : ${{ needs.stale-issue-pr.outputs.OUTCOME }}\n
              Job     : ${{ needs.stale-branch.outputs.WF_NAME }}\n
              Result  : ${{ needs.stale-branch.outputs.OUTCOME }}\n
              ```"
