---

name: notify

on:  # yamllint disable-line rule:truthy

  workflow_run:
    workflows:
      - ci
      - cd

    types:
      - completed

jobs:

  on-success:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

    - shell: bash
      # checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
      run: |
        echo "The triggering workflow passed"
        echo "Repository name           : ${{ github.repository }}"
        echo "Branch name (head_branch) : ${{ github.event.workflow_run.head_branch }}"
        echo "Source Workflow Run name  : ${{ github.event.workflow_run.name }}"
        echo "Workflow URL              : ${{ github.event.workflow_run.html_url }}"

    - name: Post message to Slack Channel
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_CICD }}"
          text: ":rocket: *Workflow Passed*\n\n```Repository name           : ${{ github.repository }}\nBranch name (head_branch) : ${{ github.event.workflow_run.head_branch }}\nSource Workflow Run name  : ${{ github.event.workflow_run.name }}\nWorkflow URL              : ${{ github.event.workflow_run.html_url }}```"

  on-failure:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:

    - shell: bash
      # checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
      run: |
        echo "The triggering workflow failed"
        echo "Repository name           : ${{ github.repository }}"
        echo "Branch name (head_branch) : ${{ github.event.workflow_run.head_branch }}"
        echo "Source Workflow Run name  : ${{ github.event.workflow_run.name }}"
        echo "Workflow URL              : ${{ github.event.workflow_run.html_url }}"

    - name: Post message to Slack Channel
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_CICD }}"
          text: ":fire: *Workflow Failed*\n\n```Repository name           : ${{ github.repository }}\nBranch name (head_branch) : ${{ github.event.workflow_run.head_branch }}\nSource Workflow Run name  : ${{ github.event.workflow_run.name }}\nWorkflow URL              : ${{ github.event.workflow_run.html_url }}```"
