---
# NOTE: this file is managed by terraform

name: notify-cicd

on:  # yamllint disable-line rule:truthy

  workflow_run:
    workflows:
      - ci
      - cd

    types:
      - completed

jobs:

  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:

    # - shell: bash
    #   # checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
    #   run: |
    #     echo "The triggering workflow passed"
    #     echo "Repo Name   : ${{ github.repository }}"
    #     echo "Branch Name : ${{ github.event.workflow_run.head_branch }}"
    #     echo "Workflow    : ${{ github.event.workflow_run.name }}"
    #     echo "Workflow URL: ${{ github.event.workflow_run.html_url }}"

    - name: Post message to Slack
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_CICD }}"
          text: ":white_check_mark: *${{ github.event.workflow_run.name }} Workflow Passed*
            ```
            Repo    : ${{ github.repository }}\n
            Branch  : ${{ github.event.workflow_run.head_branch }}\n
            Workflow: ${{ github.event.workflow_run.html_url }}
            ```"

  on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    runs-on: ubuntu-latest

    steps:

    # - shell: bash
    #   # checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
    #   run: |
    #     echo "The triggering workflow failed"
    #     echo "Repo Name   : ${{ github.repository }}"
    #     echo "Branch Name : ${{ github.event.workflow_run.head_branch }}"
    #     echo "Workflow    : ${{ github.event.workflow_run.name }}"
    #     echo "Workflow URL: ${{ github.event.workflow_run.html_url }}"

    - name: Post message to Slack
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_CICD }}"
          text: ":no_entry: *${{ github.event.workflow_run.name }} Workflow Failed*
            ```
            Repo    : ${{ github.repository }}\n
            Branch  : ${{ github.event.workflow_run.head_branch }}\n
            Workflow: ${{ github.event.workflow_run.html_url }}
            ```"
