---
# on push to main > build package > upload artifacts

name: release

on:
  pull_request:

    branches:
      - main

    types:
      - closed

  workflow_dispatch:

  # workflow_run:
  #   workflows:
  #     - testings

  #   branches:
  #     - release/*

  #   types:
  #     - completed

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest

    steps:

    - name: hello
      run: echo "hello world!!"

    - name: get github.event (JSON)
      run: echo "GH_EVENT_OBJ=${{ toJson(github.event) }}"

    - name: get github workflow (some JSON)
      run: echo "GH_WORKFLOW=${{ toJson(github.workflow) }}"

    - name: get github.event.workflow (JSON)
      run: echo "GH_WORKFLOW_OBJ=${{ toJson(github.event.workflow) }}"

    - name: get github vars (JSON)
      run: echo "GH_WORKFLOW_OBJ=${{ toJson(vars) }}"

    - name: get github.head_ref - expect 'release/x.x.x'
      run: echo "GH_HEAD_REF=${{ github.head_ref }}"

    - name: get noooooooooooooooooooo
      run: echo "---------"

    - name: get github.head_ref - expect 'success'
      run: echo "GH_HEAD_REF=${{ github.event.workflow.conclusion }}"

    - name: get github event_name
      run: echo "GH_EVENT_NAME=${{ github.event_name }}"

    - name: get others
      run: echo "others"
