---
# on push to main > build package > upload artifacts

name: release

on:
  pull_request:

    branches:
      - main

    types:
      - closed

  workflow_dispatch:

  # workflow_run:
  #   workflows:
  #     - testings

  #   branches:
  #     - release/*

  #   types:
  #     - completed

permissions:
  contents: write

jobs:
  release:
    if: startsWith(github.head_ref, 'release/')

    runs-on: ubuntu-latest

    steps:

    - name: hello
      run: echo "hello world !!"

    - name: get github events (JSON)
      run: echo "GH_EVENT_OBJ=${{ toJson(github.event) }}"

    - name: get github workflow name result
      run: echo "GH_WORKFLOW=${{ toJson(github.workflow) }}"

    - name: get github workflow_run result
      run: echo "GH_WORKFLOW_OBJ=${{ toJson(github.event.workflow) }}"

    - name: get github event_name
      run: echo "GH_EVENT_NAME=${{ github.event_name }}"

    - name: get others
      run: echo "others"
