---
# on push to main > build package > upload artifacts

name: release

on:
  # pull_request:

  #   branches:
  #     - main

  #   types:
  #     - closed

  workflow_dispatch:

  workflow_run:
    workflows:
      - testings

    branches:
      - release/*

    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    # if startsWith(github.head_ref, 'release/')

    runs-on: ubuntu-latest

    steps:

    - name: hello
      run: echo "hello world !!"

    - name: get github events (JSON)
      run: echo "GH_EVENT_OBJ=${{ toJson(github.event) }}"

    - name: get github event workflow_run result - testings
      run: echo "GH_WORKFLOW_RUN_OBJ=${{ toJson(github.event.workflow_run) }}"

    - name: get github actions workflow names
      run: echo "GH_WORKFLOW_NAME=${{ toJson(github.event_name) }}"

    - name: get others
      run: echo "others"
