---
# on push to main > build package > upload artifacts

name: release

on:
  push:
    branches:
      - test-*

  pull_request:
    types:
      - closed

    branches:
      - main

env:
  PYTHON_VERSION: '3.12.10'

jobs:
  release:

    runs-on: ubuntu-latest
    steps:

    - name: Get release version
      run: |
        # get release version
        GITREF_NAME="${{ github.ref_name }}"
        echo "Git Ref Name: $GITREF_NAME"
        exit 1

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Build and Package Application
      run: |
        # get latest build
        python -m pip install -U build

        # build package
        python -m build

        # List dist
        tree dist

    - name: Get GIT Commit HASH
      id: git_commit_hash
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

    - name: Upload distributions
      id: artifact-upload
      uses: actions/upload-artifact@v4
      with:
        name: release-dists
        path: dist/
        if-no-files-found: error
        retention-days: 3
        overwrite: true

    - name: Get Outputs
      run: |
        # get commit hash and artifact id
        echo 'Short Git Commit Hash: ${{ steps.git_commit_hash.outputs.sha_short }}'
        echo 'Upload Artifact ID   : ${{ steps.artifact-upload.outputs.artifact-id }}'
