---

name: release

on:
  # pull_request:

  #   branches:
  #     - main

  #   types:
  #     - closed

  # workflow_dispatch:

  workflow_run:
    workflows:
      - testings

    branches:
      - release/*

    types:
      - completed

permissions:
  contents: write

jobs:
  release-checks:

    runs-on: ubuntu-latest

    steps:

    - name: hello
      run: echo "hello world!!"

    - name: get github object (JSON)
      run: echo "GH_OBJ=${{ toJson(github) }}"

    - name: get github.event (JSON)
      run: echo "GH_EVENT_OBJ=${{ toJson(github.event) }}"

    - name: get github.workflow - expect release - SUCCESS
      run: echo "GH_WORKFLOW=${{ github.workflow }}"

    - name: get github.workflow.conclusion - expect success - TBD
      run: echo "GH_WORKFLOW_CONCLUSION=${{ github.workflow.conclusion }}"

    - name: get github.event_name - expect pull_request - SUCCESS
      run: echo "GH_EVENT_NAME=${{ github.event_name }}"

    - name: get github.head_ref - expect release/m.n.p.[+] - SUCCESS
      # checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
      run: echo "GH_HEAD_REF=${{ github.head_ref }}"

    - name: get others
      run: echo "others"
