---
# NOTE: this file is managed by terraform

name: testings

on:  # yamllint disable-line rule:truthy
  workflow_call:
    outputs:

      RELEASE_BRANCH_HEAD_REF:
        value: ${{ jobs.validate-release-version.outputs.RELEASE_BRANCH_HEAD_REF }}

      RELEASE_BRANCH_SPEC_VER:
        value: ${{ jobs.validate-release-version.outputs.RELEASE_BRANCH_SPEC_VER }}

      BUILD_VERSION:
        value: ${{ jobs.build.outputs.BUILD_VERSION }}

  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12.10'

permissions:
  contents: read

jobs:

  pre-ci:
    uses: ./.github/workflows/reusable-pre-commit.yaml

  build:
    runs-on: ubuntu-latest

    outputs:
      BUILD_VERSION: ${{ steps.set-build-version.outputs.BUILD_VERSION }}

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Make build
      run: make build

    - name: Set Build Version
      id: set-build-version
      run: |
        echo "BUILD_VERSION=$(python src/*/run.py --version | awk '{print $3}')" >> "$GITHUB_OUTPUT"

    - name: Get Build Version
      id: get-build-version
      run: |
        echo "Build Version: ${{ steps.set-build-version.outputs.BUILD_VERSION }}"

    - name: Upload distributions
      id: artifact-upload
      uses: actions/upload-artifact@v4
      with:
        path: dist/
        if-no-files-found: error
        retention-days: 3
        overwrite: true
        compression-level: 6

  test:
    needs: build

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install test dependencies
      run: make test-install

    - name: Make Test
      run: make test

  validate-release:
    if: ${{ startsWith(github.head_ref, 'release/') }}

    needs: [build, test, pre-ci]

    runs-on: ubuntu-latest

    outputs:
      RELEASE_BRANCH_HEAD_REF: ${{ steps.set-release-branch.outputs.GITHUB_HEAD_REF }}
      RELEASE_BRANCH_SPEC_VER: ${{ steps.set-release-branch.outputs.GITHUB_SPEC_VER }}

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - id: set-release-branch
      # checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
      shell: bash
      run: |
        # set release branch info
        GITHUB_HEAD_REF=${{ github.head_ref }}
        GITHUB_SPEC_VER=${GITHUB_HEAD_REF#release/}
        # set release branch info to job output
        echo "GITHUB_HEAD_REF=${{ github.head_ref }}"      >> "$GITHUB_OUTPUT"
        echo "GITHUB_SPEC_VER=${GITHUB_HEAD_REF#release/}" >> "$GITHUB_OUTPUT"

    - shell: bash
      run: |
        # get output variables
        echo "Release Branch Name        : ${{ steps.set-release-branch.outputs.GITHUB_HEAD_REF }}"
        echo "Release Branch Spec Version: ${{ steps.set-release-branch.outputs.GITHUB_SPEC_VER }}"
        echo "Software Build Version     : ${{ needs.build.outputs.BUILD_VERSION }}"

    - shell: bash
      run: |
        # compare release branch and software build version
        if [ "${{ needs.build.outputs.BUILD_VERSION}}" != "${{steps.set-release-branch.outputs.GITHUB_SPEC_VER}}" ]; then
          echo "Error: Release Branch Specified Version is different from Build Version."
          exit 1
        fi

    - shell: bash
      run: |
        # check duplicate tag
        TAG_EXIST="$(git ls-remote origin refs/tags/${{ needs.build.outputs.BUILD_VERSION }} | awk '{print $2}' | sed 's/refs\/tags\///g')"
        if [ -n "$TAG_EXIST" ]; then
          echo "Error: Tag ($TAG_EXIST) exists already at remote origin"
          exit 1
        fi
