---
# NOTE: this file is managed by terraform

name: dependency-review

on:  # yamllint disable-line rule:truthy
  workflow_call:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        license-check: true
        vulnerability-check: true
