---

name: notify

on:  # yamllint disable-line rule:truthy

  workflow_run:

    workflows: [ci]

    types:
      - completed

    branches:
      - main
      - release/[0-9]+.[0-9]+[0-9]+$

jobs:

  notify-channel:

    runs-on: ubuntu-latest

    steps:

    - shell: bash
      run: >-
        echo "Branch - ${{ github.head_ref }} - triggers workflow - ${{ github.event.workflow_run.name }} - with ${{ github.event.workflow_run.conclusion }}"

    - name: Post message to Slack
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: ${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}
        payload: |
          channel: ${{ secrets.SECRET_SLACK_CHANNEL_CICD }}
          text: "howdy <@channel>!"
