---

name: notify

on:  # yamllint disable-line rule:truthy

  workflow_run:

    workflows: [ci, cd]

    types:
      - completed

    branches:
      - main
      - release/[0-9]+.[0-9]+[0-9]+

jobs:

  notify-channel:

    runs-on: ubuntu-latest

    steps:

    - shell: bash
      # checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
      run: |
        echo "${{ toJson(github) }}"

    - shell: bash
      # checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
      run: |
        echo "Branch - ${{ github.head_ref }} - triggers workflow - ${{ github.event.workflow_run.name }} - with ${{ github.event.workflow_run.conclusion }}"

    - name: Post message to Slack Channel
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_CICD }}"
          text: "howdy <@channel>!"
