---
# NOTE: this file is managed by terraform

name: run-labeler

on:  # yamllint disable-line rule:truthy
  pull_request_target:

  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labeler:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}

    # https://github.com/marketplace/actions/labeler
    - id: label-pr
      uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - run: echo "${{ steps.label-pr.outputs.all-labels }}"
