---
# NOTE: this file is managed by terraform

# trigger job run on event pull_request_target
name: siderun-pr-target

on:  # yamllint disable-line rule:truthy
  pull_request_target:

  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labeler:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}

    # https://github.com/marketplace/actions/labeler
    - id: label-pr
      uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - run: echo "${{ steps.label-pr.outputs.all-labels }}"

  notify-slack:
    runs-on: ubuntu-latest

    steps:
    # - name: debug only
    #   run: echo "${{ toJson(github) }}"

    - name: Slack message on PR activities
      uses: slackapi/slack-github-action@v2.1.0
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_PR }}"
          text: ":fire: *Pull Request (re)opened or updated.*
          ```
          Repo  : ${{ github.repository }}\n
          Branch: ${{ github.event.pull_request.head.ref }}\n
          PR URL: ${{ github.event.pull_request.html_url }}
          ```"
