---

name: testings

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - test-*

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: make build
      run: make build

    - name: get build version
      id: get-build-version
      run: |
        # get build version
        echo "BUILD_VERSION=$(pkg-15903 --version | awk '{print $3}')" >> "$GITHUB_OUTPUT"
        echo $BUILD_VERSION

    outputs:
      build_version: ${{ steps.get-build-version.outputs.BUILD_VERSION }}

  test:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install test dependencies
      run: python -m pip install -e .[test]

    - name: make test
      run: make test

  validate-version:
    needs: [build, test]
    #: if startsWith(github.head_ref, 'release/')
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]

    runs-on: ubuntu-latest
    steps:

    - name: Get Outputs
      run: |
        # get various outputs
        echo 'Branch Build version.: ${{ needs.build.outputs.build_version }}'
        echo 'Branch Release name  : hello'
