name: update-pre-commit-action

on:
  # on demand
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  update-pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Run update-pre-commit
      id: update-pre-commit

      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      uses: tagdots/update-pre-commit-action@2cd407af92c1c9435c6406f4e23657d3ea14dcbb # 1.0.1

      with:
        file: .pre-commit-config.yaml
        dry-run: false
        open-pr: true
