name: upc-action-test

on:
  # on schedule: e.g. every day at 5:30 pm UTC
  schedule:
    - cron: '30 17 * * *'

  # on demand
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  update-pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Run update-pre-commit
      id: update-pre-commit
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: tagdots-dev/upc-action-test@ceebb82af3610a6f8b505a21525cc1a3fb4aa59e # 1.0.0
      with:
        file: .pre-commit-config.yaml
        dry-run: false
        open-pr: true
