name: update-pre-commit-action

on:
  # on demand
  workflow_dispatch:

  # schedule:
  #   - cron: '*/5 * * * *'

permissions:
  contents: read
  pull-requests: read

jobs:
  update-pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Run update-pre-commit
      id: update-pre-commit

      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      uses: tagdots/update-pre-commit-action@7b2124d4ac1abdaf462b2ee85312e2b564aa2709 # 1.0.27

      with:
        file: .pre-commit-config.yaml
        dry-run: true
        open-pr: false
