---
# NOTE: this file is managed by terraform

name: CICD

on:  # yamllint disable-line rule:truthy

  push:
    branches:
      - test-*

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre-ci:
    uses: ./.github/workflows/reusable-pre-commit.yaml
  tests:
    uses: ./.github/workflows/reusable-testings.yaml

  release:
    runs-on: ubuntu-latest
    needs: [pre-ci, tests]
    steps:

    - name: say hello
      run: echo "hello"

    - name: get job object
      run: |
        echo "${{ toJson(job) }}"
