---

name: workflow-tests

on:  # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:

permissions:
  contents: read

env:
  WF_ENV_VAR: 'default'

jobs:
  step-data:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]

    runs-on: ubuntu-latest

    env:
      JOB_STEP_DATA_ENV: 'hello'

    steps:
    - name: Get Outputs from github cotext
      id: get_github_object
      run: |
        # get outputs
        # parse github object into Json
        echo "GH_OBJ=${{ toJson(github) }}"

    # Test 1 - pass data across steps - FAILURE
    - name: Step 1 - Assign value to a new step variable
      id: assgin_value_to_step_1
      run: |
        # assign value to step 1
        STEP_1_GH_REF_NAME="${{ github.ref_name }}"
        echo "STEP_1_GH_REF_NAME: ${STEP_1_GH_REF_NAME}"
    - name: Step 2 - Get value from Step 1 - FAILURE
      id: get_value_from_step_1
      run: |
        # get value from step 1
        # ${STEP_1_GH_REF_NAME} is NOT passed to STEP_2_GH_REF_NAME
        # because STEP_1_GH_REF_NAME is not visible outside of Step 1
        #
        STEP_2_GH_REF_NAME=${STEP_1_GH_REF_NAME}
        echo "STEP_2_GH_REF_NAME: ${STEP_2_GH_REF_NAME}"

    # Test 2 - pass data across steps - SUCCESS
    - name: Step 3 - Assign value to a new step variable
      id: assgin_value_to_step_3
      run: |
        # assign value to step 3
        echo "STEP_3_GH_REF_NAME=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
    - name: Step 4 - Get value from Step 3 - SUCCESS
      id: get_value_from_step_3
      run: |
        # get value from step 3
        STEP_4_GH_REF_NAME="${{ steps.assgin_value_to_step_3.outputs.STEP_3_GH_REF_NAME }}"
        echo "STEP_4_GH_REF_NAME: ${STEP_4_GH_REF_NAME}"

    # Test 3 - pass data from job to steps
    - name: Step 5 - Get value from Job step-data - FAILURE
      id: get_value_from_job_step_data
      run: |
        # assign value to step 5
        echo "JOB_STEP_DATA_ENV : ${JOB_STEP_DATA_ENV}"
        #
        echo "STEP_5_JOB_DATA   : ${STEP_5_JOB_DATA}"
        echo "STEP_5_JOB_DATA=${JOB_STEP_DATA_ENV}" >> "$GITHUB_OUTPUT"
    - name: Step 6 - Get value from Job step-data - SUCCESS
      run: |
          echo "STEP_5_JOB_DATA   : ${{ steps.get_value_from_job_step_data.outputs.STEP_5_JOB_DATA }}"
