---

name: testings

on:  # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:

permissions:
  contents: read

env:
  WF_ENV_VAR: 'default'

jobs:
  step-data:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]

    runs-on: ubuntu-latest
    steps:

    - name: Get Outputs from github cotext
      id: get_github_object
      run: |
        # get outputs
        # parse github object into Json
        echo "GH_OBJ=${{ toJson(github) }}"

    - name: Step 0 - Assign value to a new step variable
      id: assgin_value_to_step_0
      run: |
        # assign value to step 0
        STEP_0_GH_REF_NAME="${{ github.ref_name }}"
        echo "STEP_0_GH_REF_NAME: ${STEP_0_GH_REF_NAME}"

    - name: Step 1 - Get value from Step 0
      id: get_value_from_step_0
      run: |
        # get value from step 0
        STEP_1_GH_REF_NAME=${STEP_0_GH_REF_NAME}
        echo "${STEP_1_GH_REF_NAME}"
